### PR TITLE
Solution for Issue #1

### PR DESCRIPTION
**Pull request by ghost**
#1

### CODE REVIEW

**Comment by qoh** [comment]
It doesn't seem like delaytest.ogg loops well

**Comment by ghost** [comment]
It doesn't, but it shouldn't matter that much, since each tap offset will still be calculated accurately as long as `source:tell()` is relied on for time.

**Comment by ItsNovaHere** [comment]
How did you pull request? I can't seem to figure out :/

**Comment by qoh** [comment]
@Theawesome624 Go to your fork of the repository, make a change to it and click the pull request button near the top.

**Comment by ItsNovaHere** [comment]
Wow, that was fast.

**Pull request merged**
